"""RmlUI DOM API"""

from collections.abc import Callable
from typing import overload


class RmlContext:
    def create_data_model(self, name: str) -> object: ...

    def remove_data_model(self, name: str) -> bool: ...

class RmlEvent:
    def type(self) -> str: ...

    def target(self) -> object: ...

    def current_target(self) -> object: ...

    def stop_propagation(self) -> None: ...

    def get_parameter(self, key: str, default_val: str = '') -> str: ...

class RmlElement:
    def get_element_by_id(self, arg: str, /) -> object: ...

    def query_selector_all(self, arg: str, /) -> list: ...

    def query_selector(self, arg: str, /) -> object: ...

    def parent(self) -> object: ...

    def children(self) -> list: ...

    def num_children(self) -> int: ...

    @overload
    def append_child(self, tag_name: str) -> object: ...

    @overload
    def append_child(self, child: RmlElement) -> object: ...

    @overload
    def insert_before(self, tag_name: str, ref_child: RmlElement) -> object: ...

    @overload
    def insert_before(self, child: RmlElement, ref_child: RmlElement) -> object: ...

    def remove_child(self, arg: RmlElement, /) -> None: ...

    def set_inner_rml(self, arg: str, /) -> None: ...

    def get_inner_rml(self) -> str: ...

    def set_text(self, arg: str, /) -> None: ...

    def set_attribute(self, arg0: str, arg1: str, /) -> None: ...

    def get_attribute(self, name: str, default_val: str = '') -> str: ...

    def has_attribute(self, arg: str, /) -> bool: ...

    def remove_attribute(self, arg: str, /) -> None: ...

    def set_class(self, arg0: str, arg1: bool, /) -> None: ...

    def is_class_set(self, arg: str, /) -> bool: ...

    def set_class_names(self, arg: str, /) -> None: ...

    def get_class_names(self) -> str: ...

    def set_property(self, arg0: str, arg1: str, /) -> bool: ...

    def remove_property(self, arg: str, /) -> None: ...

    def animate(self, property: str, target_value: str, duration: float, tween: str = 'quadratic-out', start_value: str | None = None, remove_on_complete: bool = False) -> bool: ...

    def add_event_listener(self, arg0: str, arg1: Callable, /) -> None: ...

    def set_id(self, arg: str, /) -> None: ...

    @property
    def id(self) -> str: ...

    @id.setter
    def id(self, arg: str, /) -> None: ...

    @property
    def tag_name(self) -> str: ...

    @property
    def scroll_left(self) -> float: ...

    @scroll_left.setter
    def scroll_left(self, arg: float, /) -> None: ...

    @property
    def scroll_top(self) -> float: ...

    @scroll_top.setter
    def scroll_top(self, arg: float, /) -> None: ...

    @property
    def scroll_width(self) -> float: ...

    @property
    def scroll_height(self) -> float: ...

    @property
    def client_width(self) -> float: ...

    @property
    def client_height(self) -> float: ...

    @property
    def offset_top(self) -> float: ...

    @property
    def offset_height(self) -> float: ...

    def scroll_into_view(self, align_top: bool = True) -> None: ...

    def focus(self) -> bool: ...

    def blur(self) -> None: ...

class RmlDocument(RmlElement):
    def create_element(self, arg: str, /) -> object: ...

    def create_text_node(self, arg: str, /) -> object: ...

    def show(self) -> None: ...

    def hide(self) -> None: ...

    def create_data_model(self, name: str) -> object: ...

    def remove_data_model(self, name: str) -> bool: ...

    @property
    def title(self) -> str: ...

    @title.setter
    def title(self, arg: str, /) -> None: ...

class DataModelHandle:
    def dirty(self, name: str) -> None: ...

    def dirty_all(self) -> None: ...

    def is_dirty(self, name: str) -> bool: ...

    def update_string_list(self, name: str, items: list) -> None: ...

    def update_record_list(self, name: str, items: list) -> None: ...

class DataModelConstructor:
    def bind(self, name: str, getter: Callable, setter: object | None = None) -> None: ...

    def bind_func(self, name: str, getter: Callable) -> None: ...

    def bind_event(self, name: str, callback: Callable) -> None: ...

    def register_transform(self, name: str, func: Callable) -> None: ...

    def bind_string_list(self, name: str) -> None: ...

    def bind_record_list(self, name: str) -> None: ...

    def get_handle(self) -> DataModelHandle: ...

def get_document(arg: str, /) -> object: ...
