"""Mesh operations and OpenMesh bindings"""

from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import lichtfeld


class MeshData:
    def __init__(self, vertices: lichtfeld.Tensor, indices: lichtfeld.Tensor) -> None: ...

    @property
    def vertices(self) -> lichtfeld.Tensor: ...

    @property
    def normals(self) -> lichtfeld.Tensor: ...

    @property
    def tangents(self) -> lichtfeld.Tensor: ...

    @property
    def texcoords(self) -> lichtfeld.Tensor: ...

    @property
    def colors(self) -> lichtfeld.Tensor: ...

    @property
    def indices(self) -> lichtfeld.Tensor: ...

    @property
    def vertex_count(self) -> int: ...

    @property
    def face_count(self) -> int: ...

    @property
    def has_normals(self) -> bool: ...

    @property
    def has_tangents(self) -> bool: ...

    @property
    def has_texcoords(self) -> bool: ...

    @property
    def has_colors(self) -> bool: ...

    def set_vertices(self, tensor: lichtfeld.Tensor) -> None: ...

    def set_normals(self, tensor: lichtfeld.Tensor) -> None: ...

    def set_indices(self, tensor: lichtfeld.Tensor) -> None: ...

    def set_texcoords(self, tensor: lichtfeld.Tensor) -> None: ...

    def set_colors(self, tensor: lichtfeld.Tensor) -> None: ...

    def compute_normals(self) -> None: ...

    def to(self, device: str) -> MeshData: ...

    def to_trimesh(self) -> TriMesh:
        """Convert to OpenMesh TriMesh for topology operations"""

    def __repr__(self) -> str: ...

class BaseHandle:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

    def idx(self) -> int: ...

    def is_valid(self) -> bool: ...

    def reset(self) -> None: ...

    def invalidate(self) -> None: ...

    def __eq__(self, arg: BaseHandle, /) -> bool: ...

    def __ne__(self, arg: BaseHandle, /) -> bool: ...

    def __lt__(self, arg: BaseHandle, /) -> bool: ...

class VertexHandle(BaseHandle):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

class HalfedgeHandle(BaseHandle):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

class EdgeHandle(BaseHandle):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

class FaceHandle(BaseHandle):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

class TriMesh:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, points: Annotated[NDArray[numpy.float64], dict(order='C')], face_vertex_indices: Annotated[NDArray[numpy.int32], dict(order='C')]) -> None: ...

    @overload
    def __init__(self, points: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None: ...

    def __copy__(self) -> object: ...

    def __deepcopy__(self, arg: dict, /) -> object: ...

    def reserve(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    def vertex_handle(self, arg: int, /) -> VertexHandle: ...

    @overload
    def halfedge_handle(self, arg: int, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg0: EdgeHandle, arg1: int, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg: FaceHandle, /) -> HalfedgeHandle: ...

    @overload
    def edge_handle(self, arg: int, /) -> EdgeHandle: ...

    @overload
    def edge_handle(self, arg: HalfedgeHandle, /) -> EdgeHandle: ...

    @overload
    def face_handle(self, arg: int, /) -> FaceHandle: ...

    @overload
    def face_handle(self, arg: HalfedgeHandle, /) -> FaceHandle: ...

    def clear(self) -> None: ...

    def clean(self) -> None: ...

    @overload
    def garbage_collection(self, v: bool = True, e: bool = True, f: bool = True) -> None: ...

    @overload
    def garbage_collection(self, vh_to_update: list, hh_to_update: list, fh_to_update: list, v: bool = True, e: bool = True, f: bool = True) -> None: ...

    def n_vertices(self) -> int: ...

    def n_halfedges(self) -> int: ...

    def n_edges(self) -> int: ...

    def n_faces(self) -> int: ...

    def vertices_empty(self) -> bool: ...

    def halfedges_empty(self) -> bool: ...

    def edges_empty(self) -> bool: ...

    def faces_empty(self) -> bool: ...

    @overload
    def set_halfedge_handle(self, arg0: VertexHandle, arg1: HalfedgeHandle, /) -> None: ...

    @overload
    def set_halfedge_handle(self, arg0: FaceHandle, arg1: HalfedgeHandle, /) -> None: ...

    def to_vertex_handle(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    def from_vertex_handle(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    def set_vertex_handle(self, arg0: HalfedgeHandle, arg1: VertexHandle, /) -> None: ...

    def set_face_handle(self, arg0: HalfedgeHandle, arg1: FaceHandle, /) -> None: ...

    def next_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def set_next_halfedge_handle(self, arg0: HalfedgeHandle, arg1: HalfedgeHandle, /) -> None: ...

    def prev_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def opposite_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def ccw_rotated_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def cw_rotated_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    @overload
    def is_deleted(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: FaceHandle, /) -> bool: ...

    @overload
    def set_deleted(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: HalfedgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: EdgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: FaceHandle, arg1: bool, /) -> None: ...

    def is_locked(self, arg: VertexHandle, /) -> bool: ...

    def set_locked(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    def request_vertex_normals(self) -> None: ...

    def request_vertex_colors(self) -> None: ...

    def request_vertex_texcoords1D(self) -> None: ...

    def request_vertex_texcoords2D(self) -> None: ...

    def request_vertex_texcoords3D(self) -> None: ...

    def request_halfedge_normals(self) -> None: ...

    def request_halfedge_colors(self) -> None: ...

    def request_halfedge_texcoords1D(self) -> None: ...

    def request_halfedge_texcoords2D(self) -> None: ...

    def request_halfedge_texcoords3D(self) -> None: ...

    def request_edge_colors(self) -> None: ...

    def request_face_normals(self) -> None: ...

    def request_face_colors(self) -> None: ...

    def request_face_texture_index(self) -> None: ...

    def release_vertex_normals(self) -> None: ...

    def release_vertex_colors(self) -> None: ...

    def release_vertex_texcoords1D(self) -> None: ...

    def release_vertex_texcoords2D(self) -> None: ...

    def release_vertex_texcoords3D(self) -> None: ...

    def release_halfedge_normals(self) -> None: ...

    def release_halfedge_colors(self) -> None: ...

    def release_halfedge_texcoords1D(self) -> None: ...

    def release_halfedge_texcoords2D(self) -> None: ...

    def release_halfedge_texcoords3D(self) -> None: ...

    def release_edge_colors(self) -> None: ...

    def release_face_normals(self) -> None: ...

    def release_face_colors(self) -> None: ...

    def release_face_texture_index(self) -> None: ...

    def has_vertex_normals(self) -> bool: ...

    def has_vertex_colors(self) -> bool: ...

    def has_vertex_texcoords1D(self) -> bool: ...

    def has_vertex_texcoords2D(self) -> bool: ...

    def has_vertex_texcoords3D(self) -> bool: ...

    def has_halfedge_normals(self) -> bool: ...

    def has_halfedge_colors(self) -> bool: ...

    def has_halfedge_texcoords1D(self) -> bool: ...

    def has_halfedge_texcoords2D(self) -> bool: ...

    def has_halfedge_texcoords3D(self) -> bool: ...

    def has_edge_colors(self) -> bool: ...

    def has_face_normals(self) -> bool: ...

    def has_face_colors(self) -> bool: ...

    def has_face_texture_index(self) -> bool: ...

    @overload
    def new_vertex(self) -> VertexHandle: ...

    @overload
    def new_vertex(self, arg: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> VertexHandle: ...

    def new_edge(self, arg0: VertexHandle, arg1: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def new_face(self) -> FaceHandle: ...

    @overload
    def new_face(self, arg: "OpenMesh::ArrayItems::Face", /) -> FaceHandle: ...

    def vertices(self) -> VertexIter: ...

    def halfedges(self) -> HalfedgeIter: ...

    def edges(self) -> EdgeIter: ...

    def faces(self) -> FaceIter: ...

    def svertices(self) -> VertexIter: ...

    def shalfedges(self) -> HalfedgeIter: ...

    def sedges(self) -> EdgeIter: ...

    def sfaces(self) -> FaceIter: ...

    def texture_index(self, arg: FaceHandle, /) -> int: ...

    def set_texture_index(self, arg0: FaceHandle, arg1: int, /) -> None: ...

    def texture_name(self, arg: int, /) -> str: ...

    @overload
    def set_feature(self, arg0: EdgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_feature(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    @overload
    def feature(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def feature(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def copy_all_properties(self, vh_from: VertexHandle, vh_to: VertexHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, hh_from: HalfedgeHandle, hh_to: HalfedgeHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, eh_from: EdgeHandle, eh_to: EdgeHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, fh_from: FaceHandle, fh_to: FaceHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def is_valid_handle(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: FaceHandle, /) -> bool: ...

    def delete_isolated_vertices(self) -> None: ...

    @overload
    def assign_connectivity(self, arg: PolyMesh, /) -> None: ...

    @overload
    def assign_connectivity(self, arg: TriMesh, /) -> None: ...

    @overload
    def add_face(self, arg0: VertexHandle, arg1: VertexHandle, arg2: VertexHandle, /) -> FaceHandle: ...

    @overload
    def add_face(self, arg: Sequence[VertexHandle], /) -> FaceHandle: ...

    def opposite_face_handle(self, arg: HalfedgeHandle, /) -> "OpenMesh::SmartFaceHandle": ...

    def adjust_outgoing_halfedge(self, arg: VertexHandle, /) -> None: ...

    def find_halfedge(self, arg0: VertexHandle, arg1: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def valence(self, arg: VertexHandle, /) -> int: ...

    @overload
    def valence(self, arg: FaceHandle, /) -> int: ...

    def is_simple_link(self, arg: EdgeHandle, /) -> bool: ...

    def is_simply_connected(self, arg: FaceHandle, /) -> bool: ...

    @overload
    def triangulate(self, arg: FaceHandle, /) -> None: ...

    @overload
    def triangulate(self) -> None: ...

    def split_edge(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    def split_edge_copy(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    def remove_edge(self, arg: EdgeHandle, /) -> FaceHandle: ...

    def reinsert_edge(self, arg: EdgeHandle, /) -> None: ...

    def is_collapse_ok(self, arg: HalfedgeHandle, /) -> bool: ...

    def collapse(self, arg: HalfedgeHandle, /) -> None: ...

    def add_vertex(self, arg: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> VertexHandle: ...

    def delete_vertex(self, vh: VertexHandle, delete_isolated_vertices: bool = True) -> None: ...

    def delete_edge(self, eh: EdgeHandle, delete_isolated_vertices: bool = True) -> None: ...

    def delete_face(self, fh: FaceHandle, delete_isolated_vertices: bool = True) -> None: ...

    def vv(self, arg: VertexHandle, /) -> VertexVertexIter: ...

    def vih(self, arg: VertexHandle, /) -> VertexIHalfedgeIter: ...

    def voh(self, arg: VertexHandle, /) -> VertexOHalfedgeIter: ...

    def ve(self, arg: VertexHandle, /) -> VertexEdgeIter: ...

    def vf(self, arg: VertexHandle, /) -> VertexFaceIter: ...

    def fv(self, arg: FaceHandle, /) -> FaceVertexIter: ...

    def fh(self, arg: FaceHandle, /) -> FaceHalfedgeIter: ...

    def fe(self, arg: FaceHandle, /) -> FaceEdgeIter: ...

    def ff(self, arg: FaceHandle, /) -> FaceFaceIter: ...

    def hl(self, arg: HalfedgeHandle, /) -> HalfedgeLoopIter: ...

    @overload
    def is_boundary(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_boundary(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_boundary(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_boundary(self, fh: FaceHandle, check_vertex: bool = False) -> bool: ...

    def is_manifold(self, arg: VertexHandle, /) -> bool: ...

    @staticmethod
    def is_triangles() -> bool: ...

    InvalidVertexHandle: lichtfeld.mesh.VertexHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.VertexHandle"""

    InvalidHalfedgeHandle: lichtfeld.mesh.HalfedgeHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.HalfedgeHandle"""

    InvalidEdgeHandle: lichtfeld.mesh.EdgeHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.EdgeHandle"""

    InvalidFaceHandle: lichtfeld.mesh.FaceHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.FaceHandle"""

    @overload
    def calc_edge_length(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_edge_length(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_edge_sqr_length(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_edge_sqr_length(self, arg: HalfedgeHandle, /) -> float: ...

    def calc_sector_angle(self, arg: HalfedgeHandle, /) -> float: ...

    def calc_sector_area(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle_fast(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle_fast(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle(self, arg: EdgeHandle, /) -> float: ...

    def find_feature_edges(self, angle_tresh: float = 0.767944870877505) -> int: ...

    @overload
    def split(self, arg0: FaceHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split(self, arg0: EdgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> "OpenMesh::SmartVertexHandle": ...

    @overload
    def split(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> "OpenMesh::SmartVertexHandle": ...

    @overload
    def split_copy(self, arg0: FaceHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split_copy(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split_copy(self, arg0: EdgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> "OpenMesh::SmartVertexHandle": ...

    @overload
    def split_copy(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> "OpenMesh::SmartVertexHandle": ...

    def update_normals(self) -> None: ...

    @overload
    def update_normal(self, arg: FaceHandle, /) -> None: ...

    @overload
    def update_normal(self, heh: HalfedgeHandle, feature_angle: float = 0.8) -> None: ...

    @overload
    def update_normal(self, arg: VertexHandle, /) -> None: ...

    def update_face_normals(self) -> None: ...

    def update_halfedge_normals(self, feature_angle: float = 0.8) -> None: ...

    def update_vertex_normals(self) -> None: ...

    def is_estimated_feature_edge(self, arg0: HalfedgeHandle, arg1: float, /) -> bool: ...

    @staticmethod
    def is_polymesh() -> bool: ...

    def is_trimesh() -> bool: ...

    def calc_face_normal(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    def calc_halfedge_normal(self, heh: HalfedgeHandle, feature_angle: float = 0.8) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_fast(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_correct(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_loop(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_face_centroid(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def calc_edge_vector(self, arg: EdgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def calc_edge_vector(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def calc_sector_vectors(self, arg: HalfedgeHandle, /) -> tuple[NDArray[numpy.float64], NDArray[numpy.float64]]: ...

    def calc_sector_normal(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def point(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def color(self, arg: VertexHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: EdgeHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: FaceHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def texcoord1D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord1D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord2D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord2D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord3D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord3D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def set_point(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: EdgeHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord1D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord1D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord2D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord2D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord3D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord3D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def points(self) -> NDArray[numpy.float64]: ...

    def vertex_normals(self) -> NDArray[numpy.float64]: ...

    def vertex_colors(self) -> NDArray[numpy.float32]: ...

    def vertex_texcoords1D(self) -> NDArray[numpy.float64]: ...

    def vertex_texcoords2D(self) -> NDArray[numpy.float64]: ...

    def vertex_texcoords3D(self) -> NDArray[numpy.float64]: ...

    def halfedge_normals(self) -> NDArray[numpy.float64]: ...

    def halfedge_colors(self) -> NDArray[numpy.float32]: ...

    def halfedge_texcoords1D(self) -> NDArray[numpy.float64]: ...

    def halfedge_texcoords2D(self) -> NDArray[numpy.float64]: ...

    def halfedge_texcoords3D(self) -> NDArray[numpy.float64]: ...

    def edge_colors(self) -> NDArray[numpy.float32]: ...

    def face_normals(self) -> NDArray[numpy.float64]: ...

    def face_colors(self) -> NDArray[numpy.float32]: ...

    def vertex_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def vv_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_face_indices(self) -> NDArray[numpy.int32]: ...

    def vf_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_edge_indices(self) -> NDArray[numpy.int32]: ...

    def ve_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_outgoing_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def voh_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_incoming_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def vih_indices(self) -> NDArray[numpy.int32]: ...

    def face_face_indices(self) -> NDArray[numpy.int32]: ...

    def ff_indices(self) -> NDArray[numpy.int32]: ...

    def face_edge_indices(self) -> NDArray[numpy.int32]: ...

    def fe_indices(self) -> NDArray[numpy.int32]: ...

    def face_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def fh_indices(self) -> NDArray[numpy.int32]: ...

    def edge_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def ev_indices(self) -> NDArray[numpy.int32]: ...

    def edge_face_indices(self) -> NDArray[numpy.int32]: ...

    def ef_indices(self) -> NDArray[numpy.int32]: ...

    def edge_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def eh_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def hv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_to_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def htv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_from_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def hfv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_face_indices(self) -> NDArray[numpy.int32]: ...

    def hf_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_edge_indices(self) -> NDArray[numpy.int32]: ...

    def he_indices(self) -> NDArray[numpy.int32]: ...

    def add_vertices(self, points: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None: ...

    def add_faces(self, face_vertex_indices: Annotated[NDArray[numpy.int32], dict(order='C')]) -> None: ...

    def resize_points(self, arg: int, /) -> None: ...

    @overload
    def vertex_property(self, arg0: str, arg1: VertexHandle, /) -> object: ...

    @overload
    def vertex_property(self, arg: str, /) -> list: ...

    @overload
    def halfedge_property(self, arg0: str, arg1: HalfedgeHandle, /) -> object: ...

    @overload
    def halfedge_property(self, arg: str, /) -> list: ...

    @overload
    def edge_property(self, arg0: str, arg1: EdgeHandle, /) -> object: ...

    @overload
    def edge_property(self, arg: str, /) -> list: ...

    @overload
    def face_property(self, arg0: str, arg1: FaceHandle, /) -> object: ...

    @overload
    def face_property(self, arg: str, /) -> list: ...

    @overload
    def set_vertex_property(self, arg0: str, arg1: VertexHandle, arg2: object, /) -> None: ...

    @overload
    def set_vertex_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_halfedge_property(self, arg0: str, arg1: HalfedgeHandle, arg2: object, /) -> None: ...

    @overload
    def set_halfedge_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_edge_property(self, arg0: str, arg1: EdgeHandle, arg2: object, /) -> None: ...

    @overload
    def set_edge_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_face_property(self, arg0: str, arg1: FaceHandle, arg2: object, /) -> None: ...

    @overload
    def set_face_property(self, arg0: str, arg1: list, /) -> None: ...

    def has_vertex_property(self, arg: str, /) -> bool: ...

    def has_halfedge_property(self, arg: str, /) -> bool: ...

    def has_edge_property(self, arg: str, /) -> bool: ...

    def has_face_property(self, arg: str, /) -> bool: ...

    def remove_vertex_property(self, arg: str, /) -> None: ...

    def remove_halfedge_property(self, arg: str, /) -> None: ...

    def remove_edge_property(self, arg: str, /) -> None: ...

    def remove_face_property(self, arg: str, /) -> None: ...

    def vertex_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def halfedge_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def edge_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def face_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def set_vertex_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_halfedge_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_edge_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_face_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: VertexHandle, arg2: VertexHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: HalfedgeHandle, arg2: HalfedgeHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: EdgeHandle, arg2: EdgeHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: FaceHandle, arg2: FaceHandle, /) -> None: ...

    def opposite_vh(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    def opposite_he_opposite_vh(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    @overload
    def vertex_split(self, arg0: VertexHandle, arg1: VertexHandle, arg2: VertexHandle, arg3: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def vertex_split(self, arg0: Annotated[NDArray[numpy.float64], dict(order='C')], arg1: VertexHandle, arg2: VertexHandle, arg3: VertexHandle, /) -> HalfedgeHandle: ...

    def is_flip_ok(self, arg: EdgeHandle, /) -> bool: ...

    def flip(self, arg: EdgeHandle, /) -> None: ...

    def face_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def fv_indices(self) -> NDArray[numpy.int32]: ...

class PolyMesh:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, points: Annotated[NDArray[numpy.float64], dict(order='C')], face_vertex_indices: Annotated[NDArray[numpy.int32], dict(order='C')]) -> None: ...

    @overload
    def __init__(self, points: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None: ...

    def __copy__(self) -> object: ...

    def __deepcopy__(self, arg: dict, /) -> object: ...

    def reserve(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    def vertex_handle(self, arg: int, /) -> VertexHandle: ...

    @overload
    def halfedge_handle(self, arg: int, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg0: EdgeHandle, arg1: int, /) -> HalfedgeHandle: ...

    @overload
    def halfedge_handle(self, arg: FaceHandle, /) -> HalfedgeHandle: ...

    @overload
    def edge_handle(self, arg: int, /) -> EdgeHandle: ...

    @overload
    def edge_handle(self, arg: HalfedgeHandle, /) -> EdgeHandle: ...

    @overload
    def face_handle(self, arg: int, /) -> FaceHandle: ...

    @overload
    def face_handle(self, arg: HalfedgeHandle, /) -> FaceHandle: ...

    def clear(self) -> None: ...

    def clean(self) -> None: ...

    @overload
    def garbage_collection(self, v: bool = True, e: bool = True, f: bool = True) -> None: ...

    @overload
    def garbage_collection(self, vh_to_update: list, hh_to_update: list, fh_to_update: list, v: bool = True, e: bool = True, f: bool = True) -> None: ...

    def n_vertices(self) -> int: ...

    def n_halfedges(self) -> int: ...

    def n_edges(self) -> int: ...

    def n_faces(self) -> int: ...

    def vertices_empty(self) -> bool: ...

    def halfedges_empty(self) -> bool: ...

    def edges_empty(self) -> bool: ...

    def faces_empty(self) -> bool: ...

    @overload
    def set_halfedge_handle(self, arg0: VertexHandle, arg1: HalfedgeHandle, /) -> None: ...

    @overload
    def set_halfedge_handle(self, arg0: FaceHandle, arg1: HalfedgeHandle, /) -> None: ...

    def to_vertex_handle(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    def from_vertex_handle(self, arg: HalfedgeHandle, /) -> VertexHandle: ...

    def set_vertex_handle(self, arg0: HalfedgeHandle, arg1: VertexHandle, /) -> None: ...

    def set_face_handle(self, arg0: HalfedgeHandle, arg1: FaceHandle, /) -> None: ...

    def next_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def set_next_halfedge_handle(self, arg0: HalfedgeHandle, arg1: HalfedgeHandle, /) -> None: ...

    def prev_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def opposite_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def ccw_rotated_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def cw_rotated_halfedge_handle(self, arg: HalfedgeHandle, /) -> HalfedgeHandle: ...

    @overload
    def is_deleted(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_deleted(self, arg: FaceHandle, /) -> bool: ...

    @overload
    def set_deleted(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: HalfedgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: EdgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_deleted(self, arg0: FaceHandle, arg1: bool, /) -> None: ...

    def is_locked(self, arg: VertexHandle, /) -> bool: ...

    def set_locked(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    def request_vertex_normals(self) -> None: ...

    def request_vertex_colors(self) -> None: ...

    def request_vertex_texcoords1D(self) -> None: ...

    def request_vertex_texcoords2D(self) -> None: ...

    def request_vertex_texcoords3D(self) -> None: ...

    def request_halfedge_normals(self) -> None: ...

    def request_halfedge_colors(self) -> None: ...

    def request_halfedge_texcoords1D(self) -> None: ...

    def request_halfedge_texcoords2D(self) -> None: ...

    def request_halfedge_texcoords3D(self) -> None: ...

    def request_edge_colors(self) -> None: ...

    def request_face_normals(self) -> None: ...

    def request_face_colors(self) -> None: ...

    def request_face_texture_index(self) -> None: ...

    def release_vertex_normals(self) -> None: ...

    def release_vertex_colors(self) -> None: ...

    def release_vertex_texcoords1D(self) -> None: ...

    def release_vertex_texcoords2D(self) -> None: ...

    def release_vertex_texcoords3D(self) -> None: ...

    def release_halfedge_normals(self) -> None: ...

    def release_halfedge_colors(self) -> None: ...

    def release_halfedge_texcoords1D(self) -> None: ...

    def release_halfedge_texcoords2D(self) -> None: ...

    def release_halfedge_texcoords3D(self) -> None: ...

    def release_edge_colors(self) -> None: ...

    def release_face_normals(self) -> None: ...

    def release_face_colors(self) -> None: ...

    def release_face_texture_index(self) -> None: ...

    def has_vertex_normals(self) -> bool: ...

    def has_vertex_colors(self) -> bool: ...

    def has_vertex_texcoords1D(self) -> bool: ...

    def has_vertex_texcoords2D(self) -> bool: ...

    def has_vertex_texcoords3D(self) -> bool: ...

    def has_halfedge_normals(self) -> bool: ...

    def has_halfedge_colors(self) -> bool: ...

    def has_halfedge_texcoords1D(self) -> bool: ...

    def has_halfedge_texcoords2D(self) -> bool: ...

    def has_halfedge_texcoords3D(self) -> bool: ...

    def has_edge_colors(self) -> bool: ...

    def has_face_normals(self) -> bool: ...

    def has_face_colors(self) -> bool: ...

    def has_face_texture_index(self) -> bool: ...

    @overload
    def new_vertex(self) -> VertexHandle: ...

    @overload
    def new_vertex(self, arg: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> VertexHandle: ...

    def new_edge(self, arg0: VertexHandle, arg1: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def new_face(self) -> FaceHandle: ...

    @overload
    def new_face(self, arg: "OpenMesh::ArrayItems::Face", /) -> FaceHandle: ...

    def vertices(self) -> VertexIter: ...

    def halfedges(self) -> HalfedgeIter: ...

    def edges(self) -> EdgeIter: ...

    def faces(self) -> FaceIter: ...

    def svertices(self) -> VertexIter: ...

    def shalfedges(self) -> HalfedgeIter: ...

    def sedges(self) -> EdgeIter: ...

    def sfaces(self) -> FaceIter: ...

    def texture_index(self, arg: FaceHandle, /) -> int: ...

    def set_texture_index(self, arg0: FaceHandle, arg1: int, /) -> None: ...

    def texture_name(self, arg: int, /) -> str: ...

    @overload
    def set_feature(self, arg0: EdgeHandle, arg1: bool, /) -> None: ...

    @overload
    def set_feature(self, arg0: VertexHandle, arg1: bool, /) -> None: ...

    @overload
    def feature(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def feature(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def copy_all_properties(self, vh_from: VertexHandle, vh_to: VertexHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, hh_from: HalfedgeHandle, hh_to: HalfedgeHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, eh_from: EdgeHandle, eh_to: EdgeHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def copy_all_properties(self, fh_from: FaceHandle, fh_to: FaceHandle, copy_build_in: bool = False) -> None: ...

    @overload
    def is_valid_handle(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_valid_handle(self, arg: FaceHandle, /) -> bool: ...

    def delete_isolated_vertices(self) -> None: ...

    @overload
    def assign_connectivity(self, arg: PolyMesh, /) -> None: ...

    @overload
    def assign_connectivity(self, arg: TriMesh, /) -> None: ...

    @overload
    def add_face(self, arg0: VertexHandle, arg1: VertexHandle, arg2: VertexHandle, /) -> FaceHandle: ...

    @overload
    def add_face(self, arg: Sequence[VertexHandle], /) -> FaceHandle: ...

    @overload
    def add_face(self, arg0: VertexHandle, arg1: VertexHandle, arg2: VertexHandle, arg3: VertexHandle, /) -> FaceHandle: ...

    def opposite_face_handle(self, arg: HalfedgeHandle, /) -> "OpenMesh::SmartFaceHandle": ...

    def adjust_outgoing_halfedge(self, arg: VertexHandle, /) -> None: ...

    def find_halfedge(self, arg0: VertexHandle, arg1: VertexHandle, /) -> HalfedgeHandle: ...

    @overload
    def valence(self, arg: VertexHandle, /) -> int: ...

    @overload
    def valence(self, arg: FaceHandle, /) -> int: ...

    def is_simple_link(self, arg: EdgeHandle, /) -> bool: ...

    def is_simply_connected(self, arg: FaceHandle, /) -> bool: ...

    @overload
    def triangulate(self, arg: FaceHandle, /) -> None: ...

    @overload
    def triangulate(self) -> None: ...

    def split_edge(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    def split_edge_copy(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    def remove_edge(self, arg: EdgeHandle, /) -> FaceHandle: ...

    def reinsert_edge(self, arg: EdgeHandle, /) -> None: ...

    def is_collapse_ok(self, arg: HalfedgeHandle, /) -> bool: ...

    def collapse(self, arg: HalfedgeHandle, /) -> None: ...

    def add_vertex(self, arg: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> VertexHandle: ...

    def delete_vertex(self, vh: VertexHandle, delete_isolated_vertices: bool = True) -> None: ...

    def delete_edge(self, eh: EdgeHandle, delete_isolated_vertices: bool = True) -> None: ...

    def delete_face(self, fh: FaceHandle, delete_isolated_vertices: bool = True) -> None: ...

    def vv(self, arg: VertexHandle, /) -> VertexVertexIter: ...

    def vih(self, arg: VertexHandle, /) -> VertexIHalfedgeIter: ...

    def voh(self, arg: VertexHandle, /) -> VertexOHalfedgeIter: ...

    def ve(self, arg: VertexHandle, /) -> VertexEdgeIter: ...

    def vf(self, arg: VertexHandle, /) -> VertexFaceIter: ...

    def fv(self, arg: FaceHandle, /) -> FaceVertexIter: ...

    def fh(self, arg: FaceHandle, /) -> FaceHalfedgeIter: ...

    def fe(self, arg: FaceHandle, /) -> FaceEdgeIter: ...

    def ff(self, arg: FaceHandle, /) -> FaceFaceIter: ...

    def hl(self, arg: HalfedgeHandle, /) -> HalfedgeLoopIter: ...

    @overload
    def is_boundary(self, arg: HalfedgeHandle, /) -> bool: ...

    @overload
    def is_boundary(self, arg: EdgeHandle, /) -> bool: ...

    @overload
    def is_boundary(self, arg: VertexHandle, /) -> bool: ...

    @overload
    def is_boundary(self, fh: FaceHandle, check_vertex: bool = False) -> bool: ...

    def is_manifold(self, arg: VertexHandle, /) -> bool: ...

    @staticmethod
    def is_triangles() -> bool: ...

    InvalidVertexHandle: lichtfeld.mesh.VertexHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.VertexHandle"""

    InvalidHalfedgeHandle: lichtfeld.mesh.HalfedgeHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.HalfedgeHandle"""

    InvalidEdgeHandle: lichtfeld.mesh.EdgeHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.EdgeHandle"""

    InvalidFaceHandle: lichtfeld.mesh.FaceHandle = ...
    """(arg: object, /) -> lichtfeld.mesh.FaceHandle"""

    @overload
    def calc_edge_length(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_edge_length(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_edge_sqr_length(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_edge_sqr_length(self, arg: HalfedgeHandle, /) -> float: ...

    def calc_sector_angle(self, arg: HalfedgeHandle, /) -> float: ...

    def calc_sector_area(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle_fast(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle_fast(self, arg: EdgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle(self, arg: HalfedgeHandle, /) -> float: ...

    @overload
    def calc_dihedral_angle(self, arg: EdgeHandle, /) -> float: ...

    def find_feature_edges(self, angle_tresh: float = 0.767944870877505) -> int: ...

    @overload
    def split(self, arg0: FaceHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split(self, arg0: EdgeHandle, arg1: VertexHandle, /) -> None: ...

    @overload
    def split(self, arg0: EdgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def split(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def split_copy(self, arg0: FaceHandle, arg1: VertexHandle, /) -> None: ...

    def update_normals(self) -> None: ...

    @overload
    def update_normal(self, arg: FaceHandle, /) -> None: ...

    @overload
    def update_normal(self, heh: HalfedgeHandle, feature_angle: float = 0.8) -> None: ...

    @overload
    def update_normal(self, arg: VertexHandle, /) -> None: ...

    def update_face_normals(self) -> None: ...

    def update_halfedge_normals(self, feature_angle: float = 0.8) -> None: ...

    def update_vertex_normals(self) -> None: ...

    def is_estimated_feature_edge(self, arg0: HalfedgeHandle, arg1: float, /) -> bool: ...

    @staticmethod
    def is_polymesh() -> bool: ...

    def is_trimesh() -> bool: ...

    @overload
    def calc_face_normal(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def calc_face_normal(self, arg0: Annotated[NDArray[numpy.float64], dict(order='C')], arg1: Annotated[NDArray[numpy.float64], dict(order='C')], arg2: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> NDArray[numpy.float64]: ...

    def calc_halfedge_normal(self, heh: HalfedgeHandle, feature_angle: float = 0.8) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_fast(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_correct(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_vertex_normal_loop(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    def calc_face_centroid(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def calc_edge_vector(self, arg: EdgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def calc_edge_vector(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def calc_sector_vectors(self, arg: HalfedgeHandle, /) -> tuple[NDArray[numpy.float64], NDArray[numpy.float64]]: ...

    def calc_sector_normal(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def point(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def normal(self, arg: FaceHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def color(self, arg: VertexHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: EdgeHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def color(self, arg: FaceHandle, /) -> NDArray[numpy.float32]: ...

    @overload
    def texcoord1D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord1D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord2D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord2D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord3D(self, arg: VertexHandle, /) -> NDArray[numpy.float64]: ...

    @overload
    def texcoord3D(self, arg: HalfedgeHandle, /) -> NDArray[numpy.float64]: ...

    def set_point(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_normal(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: EdgeHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_color(self, arg0: FaceHandle, arg1: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord1D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord1D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord2D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord2D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord3D(self, arg0: VertexHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def set_texcoord3D(self, arg0: HalfedgeHandle, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def points(self) -> NDArray[numpy.float64]: ...

    def vertex_normals(self) -> NDArray[numpy.float64]: ...

    def vertex_colors(self) -> NDArray[numpy.float32]: ...

    def vertex_texcoords1D(self) -> NDArray[numpy.float64]: ...

    def vertex_texcoords2D(self) -> NDArray[numpy.float64]: ...

    def vertex_texcoords3D(self) -> NDArray[numpy.float64]: ...

    def halfedge_normals(self) -> NDArray[numpy.float64]: ...

    def halfedge_colors(self) -> NDArray[numpy.float32]: ...

    def halfedge_texcoords1D(self) -> NDArray[numpy.float64]: ...

    def halfedge_texcoords2D(self) -> NDArray[numpy.float64]: ...

    def halfedge_texcoords3D(self) -> NDArray[numpy.float64]: ...

    def edge_colors(self) -> NDArray[numpy.float32]: ...

    def face_normals(self) -> NDArray[numpy.float64]: ...

    def face_colors(self) -> NDArray[numpy.float32]: ...

    def vertex_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def vv_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_face_indices(self) -> NDArray[numpy.int32]: ...

    def vf_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_edge_indices(self) -> NDArray[numpy.int32]: ...

    def ve_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_outgoing_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def voh_indices(self) -> NDArray[numpy.int32]: ...

    def vertex_incoming_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def vih_indices(self) -> NDArray[numpy.int32]: ...

    def face_face_indices(self) -> NDArray[numpy.int32]: ...

    def ff_indices(self) -> NDArray[numpy.int32]: ...

    def face_edge_indices(self) -> NDArray[numpy.int32]: ...

    def fe_indices(self) -> NDArray[numpy.int32]: ...

    def face_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def fh_indices(self) -> NDArray[numpy.int32]: ...

    def edge_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def ev_indices(self) -> NDArray[numpy.int32]: ...

    def edge_face_indices(self) -> NDArray[numpy.int32]: ...

    def ef_indices(self) -> NDArray[numpy.int32]: ...

    def edge_halfedge_indices(self) -> NDArray[numpy.int32]: ...

    def eh_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def hv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_to_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def htv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_from_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def hfv_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_face_indices(self) -> NDArray[numpy.int32]: ...

    def hf_indices(self) -> NDArray[numpy.int32]: ...

    def halfedge_edge_indices(self) -> NDArray[numpy.int32]: ...

    def he_indices(self) -> NDArray[numpy.int32]: ...

    def add_vertices(self, points: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None: ...

    def add_faces(self, face_vertex_indices: Annotated[NDArray[numpy.int32], dict(order='C')]) -> None: ...

    def resize_points(self, arg: int, /) -> None: ...

    @overload
    def vertex_property(self, arg0: str, arg1: VertexHandle, /) -> object: ...

    @overload
    def vertex_property(self, arg: str, /) -> list: ...

    @overload
    def halfedge_property(self, arg0: str, arg1: HalfedgeHandle, /) -> object: ...

    @overload
    def halfedge_property(self, arg: str, /) -> list: ...

    @overload
    def edge_property(self, arg0: str, arg1: EdgeHandle, /) -> object: ...

    @overload
    def edge_property(self, arg: str, /) -> list: ...

    @overload
    def face_property(self, arg0: str, arg1: FaceHandle, /) -> object: ...

    @overload
    def face_property(self, arg: str, /) -> list: ...

    @overload
    def set_vertex_property(self, arg0: str, arg1: VertexHandle, arg2: object, /) -> None: ...

    @overload
    def set_vertex_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_halfedge_property(self, arg0: str, arg1: HalfedgeHandle, arg2: object, /) -> None: ...

    @overload
    def set_halfedge_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_edge_property(self, arg0: str, arg1: EdgeHandle, arg2: object, /) -> None: ...

    @overload
    def set_edge_property(self, arg0: str, arg1: list, /) -> None: ...

    @overload
    def set_face_property(self, arg0: str, arg1: FaceHandle, arg2: object, /) -> None: ...

    @overload
    def set_face_property(self, arg0: str, arg1: list, /) -> None: ...

    def has_vertex_property(self, arg: str, /) -> bool: ...

    def has_halfedge_property(self, arg: str, /) -> bool: ...

    def has_edge_property(self, arg: str, /) -> bool: ...

    def has_face_property(self, arg: str, /) -> bool: ...

    def remove_vertex_property(self, arg: str, /) -> None: ...

    def remove_halfedge_property(self, arg: str, /) -> None: ...

    def remove_edge_property(self, arg: str, /) -> None: ...

    def remove_face_property(self, arg: str, /) -> None: ...

    def vertex_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def halfedge_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def edge_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def face_property_array(self, arg: str, /) -> NDArray[numpy.float64]: ...

    def set_vertex_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_halfedge_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_edge_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    def set_face_property_array(self, arg0: str, arg1: Annotated[NDArray[numpy.float64], dict(order='C')], /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: VertexHandle, arg2: VertexHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: HalfedgeHandle, arg2: HalfedgeHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: EdgeHandle, arg2: EdgeHandle, /) -> None: ...

    @overload
    def copy_property(self, arg0: str, arg1: FaceHandle, arg2: FaceHandle, /) -> None: ...

    def insert_edge(self, arg0: HalfedgeHandle, arg1: HalfedgeHandle, /) -> HalfedgeHandle: ...

    def face_vertex_indices(self) -> NDArray[numpy.int32]: ...

    def fv_indices(self) -> NDArray[numpy.int32]: ...

class VertexIter:
    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartVertexHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartVertexHandle", arg2: bool, /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartVertexHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartVertexHandle", arg2: bool, /) -> None: ...

    def __iter__(self) -> VertexIter: ...

    def __next__(self) -> VertexHandle: ...

    def __len__(self) -> int: ...

class HalfedgeIter:
    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartHalfedgeHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartHalfedgeHandle", arg2: bool, /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartHalfedgeHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartHalfedgeHandle", arg2: bool, /) -> None: ...

    def __iter__(self) -> HalfedgeIter: ...

    def __next__(self) -> HalfedgeHandle: ...

    def __len__(self) -> int: ...

class EdgeIter:
    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartEdgeHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartEdgeHandle", arg2: bool, /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartEdgeHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartEdgeHandle", arg2: bool, /) -> None: ...

    def __iter__(self) -> EdgeIter: ...

    def __next__(self) -> EdgeHandle: ...

    def __len__(self) -> int: ...

class FaceIter:
    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartFaceHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: "OpenMesh::SmartFaceHandle", arg2: bool, /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartFaceHandle", /) -> None: ...

    @overload
    def __init__(self, arg0: TriMesh, arg1: "OpenMesh::SmartFaceHandle", arg2: bool, /) -> None: ...

    def __iter__(self) -> FaceIter: ...

    def __next__(self) -> FaceHandle: ...

    def __len__(self) -> int: ...

class VertexVertexIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: VertexHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: VertexHandle, /) -> None: ...

    def __iter__(self) -> VertexVertexIter: ...

    def __next__(self) -> VertexHandle: ...

class VertexIHalfedgeIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: VertexHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: VertexHandle, /) -> None: ...

    def __iter__(self) -> VertexIHalfedgeIter: ...

    def __next__(self) -> HalfedgeHandle: ...

class VertexOHalfedgeIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: VertexHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: VertexHandle, /) -> None: ...

    def __iter__(self) -> VertexOHalfedgeIter: ...

    def __next__(self) -> HalfedgeHandle: ...

class VertexEdgeIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: VertexHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: VertexHandle, /) -> None: ...

    def __iter__(self) -> VertexEdgeIter: ...

    def __next__(self) -> EdgeHandle: ...

class VertexFaceIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: VertexHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: VertexHandle, /) -> None: ...

    def __iter__(self) -> VertexFaceIter: ...

    def __next__(self) -> FaceHandle: ...

class FaceVertexIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: FaceHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: FaceHandle, /) -> None: ...

    def __iter__(self) -> FaceVertexIter: ...

    def __next__(self) -> VertexHandle: ...

class FaceHalfedgeIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: FaceHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: FaceHandle, /) -> None: ...

    def __iter__(self) -> FaceHalfedgeIter: ...

    def __next__(self) -> HalfedgeHandle: ...

class FaceEdgeIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: FaceHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: FaceHandle, /) -> None: ...

    def __iter__(self) -> FaceEdgeIter: ...

    def __next__(self) -> EdgeHandle: ...

class FaceFaceIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: FaceHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: FaceHandle, /) -> None: ...

    def __iter__(self) -> FaceFaceIter: ...

    def __next__(self) -> FaceHandle: ...

class HalfedgeLoopIter:
    @overload
    def __init__(self, arg0: TriMesh, arg1: HalfedgeHandle, /) -> None: ...

    @overload
    def __init__(self, arg0: PolyMesh, arg1: HalfedgeHandle, /) -> None: ...

    def __iter__(self) -> HalfedgeLoopIter: ...

    def __next__(self) -> HalfedgeHandle: ...

def read_trimesh(filename: str, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = False, face_texture_index: bool = False, color_alpha: bool = False, color_float: bool = False, vertex_status: bool = False, halfedge_status: bool = False, edge_status: bool = False, face_status: bool = False) -> TriMesh: ...

def read_polymesh(filename: str, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = False, face_texture_index: bool = False, color_alpha: bool = False, color_float: bool = False, vertex_status: bool = False, halfedge_status: bool = False, edge_status: bool = False, face_status: bool = False) -> PolyMesh: ...

@overload
def write_mesh(filename: str, mesh: TriMesh, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = False, color_alpha: bool = False, color_float: bool = False, status: bool = False) -> None: ...

@overload
def write_mesh(filename: str, mesh: PolyMesh, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = False, color_alpha: bool = False, color_float: bool = False, status: bool = False) -> None: ...

@overload
def write_mesh(mesh_data: MeshData, path: str) -> None:
    """Write MeshData to a mesh file"""

class TriMeshDecimater:
    def __init__(self, arg: TriMesh, /) -> None: ...

    def decimate(self, n_collapses: int = 0, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def decimate_to(self, n_vertices: int, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def decimate_to_faces(self, n_vertices: int = 0, n_faces: int = 0, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def initialize(self) -> bool: ...

    def is_initialized(self) -> bool: ...

    @overload
    def add(self, arg: TriMeshModAspectRatioHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModEdgeLengthHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModHausdorffHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModIndependentSetsHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModNormalDeviationHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModNormalFlippingHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModProgMeshHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModQuadricHandle, /) -> bool: ...

    @overload
    def add(self, arg: TriMeshModRoundnessHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModAspectRatioHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModEdgeLengthHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModHausdorffHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModIndependentSetsHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModNormalDeviationHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModNormalFlippingHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModProgMeshHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModQuadricHandle, /) -> bool: ...

    @overload
    def remove(self, arg: TriMeshModRoundnessHandle, /) -> bool: ...

    @overload
    def module(self, arg: TriMeshModAspectRatioHandle, /) -> TriMeshModAspectRatio: ...

    @overload
    def module(self, arg: TriMeshModEdgeLengthHandle, /) -> TriMeshModEdgeLength: ...

    @overload
    def module(self, arg: TriMeshModHausdorffHandle, /) -> TriMeshModHausdorff: ...

    @overload
    def module(self, arg: TriMeshModIndependentSetsHandle, /) -> TriMeshModIndependentSets: ...

    @overload
    def module(self, arg: TriMeshModNormalDeviationHandle, /) -> TriMeshModNormalDeviation: ...

    @overload
    def module(self, arg: TriMeshModNormalFlippingHandle, /) -> TriMeshModNormalFlipping: ...

    @overload
    def module(self, arg: TriMeshModProgMeshHandle, /) -> TriMeshModProgMesh: ...

    @overload
    def module(self, arg: TriMeshModQuadricHandle, /) -> TriMeshModQuadric: ...

    @overload
    def module(self, arg: TriMeshModRoundnessHandle, /) -> TriMeshModRoundness: ...

class TriMeshModBase:
    def name(self) -> str: ...

    def is_binary(self) -> bool: ...

    def set_binary(self, arg: bool, /) -> None: ...

    def initialize(self) -> None: ...

    def collapse_priority(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::TriMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> float: ...

    def preprocess_collapse(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::TriMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> None: ...

    def postprocess_collapse(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::TriMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> None: ...

    def set_error_tolerance_factor(self, arg: float, /) -> None: ...

class TriMeshModAspectRatio(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def aspect_ratio(self) -> float: ...

    def set_aspect_ratio(self, arg: float, /) -> None: ...

class TriMeshModAspectRatioHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModEdgeLength(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def edge_length(self) -> float: ...

    def set_edge_length(self, arg: float, /) -> None: ...

class TriMeshModEdgeLengthHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModHausdorff(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def tolerance(self) -> float: ...

    def set_tolerance(self, arg: float, /) -> None: ...

class TriMeshModHausdorffHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModIndependentSets(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

class TriMeshModIndependentSetsHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModNormalDeviation(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def normal_deviation(self) -> float: ...

    def set_normal_deviation(self, arg: float, /) -> None: ...

class TriMeshModNormalDeviationHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModNormalFlipping(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def max_normal_deviation(self) -> float: ...

    def set_max_normal_deviation(self, arg: float, /) -> None: ...

class TriMeshModNormalFlippingHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModProgMeshInfo:
    @property
    def v0(self) -> VertexHandle: ...

    @v0.setter
    def v0(self, arg: VertexHandle, /) -> None: ...

    @property
    def v1(self) -> VertexHandle: ...

    @v1.setter
    def v1(self, arg: VertexHandle, /) -> None: ...

    @property
    def vl(self) -> VertexHandle: ...

    @vl.setter
    def vl(self, arg: VertexHandle, /) -> None: ...

    @property
    def vr(self) -> VertexHandle: ...

    @vr.setter
    def vr(self, arg: VertexHandle, /) -> None: ...

class TriMeshModProgMesh(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def pmi(self) -> list: ...

    def infolist(self) -> list: ...

    def write(self, arg: str, /) -> bool: ...

class TriMeshModProgMeshHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModQuadric(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def set_max_err(self, err: float, binary: bool = True) -> None: ...

    def unset_max_err(self) -> None: ...

    def max_err(self) -> float: ...

class TriMeshModQuadricHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class TriMeshModRoundness(TriMeshModBase):
    def __init__(self, arg: TriMesh, /) -> None: ...

    def set_min_angle(self, arg0: float, arg1: bool, /) -> None: ...

    def set_min_roundness(self, min_roundness: float, binary: bool = True) -> None: ...

    def unset_min_roundness(self) -> None: ...

    def roundness(self, arg0: "OpenMesh::VectorT<float, 3>", arg1: "OpenMesh::VectorT<float, 3>", arg2: "OpenMesh::VectorT<float, 3>", /) -> float: ...

class TriMeshModRoundnessHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshDecimater:
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def decimate(self, n_collapses: int = 0, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def decimate_to(self, n_vertices: int, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def decimate_to_faces(self, n_vertices: int = 0, n_faces: int = 0, locked_vertex_propname: object | None = None, feature_vertex_propname: object | None = None, feature_edge_propname: object | None = None) -> None: ...

    def initialize(self) -> bool: ...

    def is_initialized(self) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModAspectRatioHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModEdgeLengthHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModHausdorffHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModIndependentSetsHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModNormalDeviationHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModNormalFlippingHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModProgMeshHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModQuadricHandle, /) -> bool: ...

    @overload
    def add(self, arg: PolyMeshModRoundnessHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModAspectRatioHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModEdgeLengthHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModHausdorffHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModIndependentSetsHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModNormalDeviationHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModNormalFlippingHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModProgMeshHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModQuadricHandle, /) -> bool: ...

    @overload
    def remove(self, arg: PolyMeshModRoundnessHandle, /) -> bool: ...

    @overload
    def module(self, arg: PolyMeshModAspectRatioHandle, /) -> PolyMeshModAspectRatio: ...

    @overload
    def module(self, arg: PolyMeshModEdgeLengthHandle, /) -> PolyMeshModEdgeLength: ...

    @overload
    def module(self, arg: PolyMeshModHausdorffHandle, /) -> PolyMeshModHausdorff: ...

    @overload
    def module(self, arg: PolyMeshModIndependentSetsHandle, /) -> PolyMeshModIndependentSets: ...

    @overload
    def module(self, arg: PolyMeshModNormalDeviationHandle, /) -> PolyMeshModNormalDeviation: ...

    @overload
    def module(self, arg: PolyMeshModNormalFlippingHandle, /) -> PolyMeshModNormalFlipping: ...

    @overload
    def module(self, arg: PolyMeshModProgMeshHandle, /) -> PolyMeshModProgMesh: ...

    @overload
    def module(self, arg: PolyMeshModQuadricHandle, /) -> PolyMeshModQuadric: ...

    @overload
    def module(self, arg: PolyMeshModRoundnessHandle, /) -> PolyMeshModRoundness: ...

class PolyMeshModBase:
    def name(self) -> str: ...

    def is_binary(self) -> bool: ...

    def set_binary(self, arg: bool, /) -> None: ...

    def initialize(self) -> None: ...

    def collapse_priority(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::PolyMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> float: ...

    def preprocess_collapse(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::PolyMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> None: ...

    def postprocess_collapse(self, arg: "OpenMesh::Decimater::CollapseInfoT<lfs::python::openmesh_bindings::MeshWrapperT<OpenMesh::PolyMesh_ArrayKernelT<lfs::python::openmesh_bindings::MeshTraits> > >", /) -> None: ...

    def set_error_tolerance_factor(self, arg: float, /) -> None: ...

class PolyMeshModAspectRatio(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def aspect_ratio(self) -> float: ...

    def set_aspect_ratio(self, arg: float, /) -> None: ...

class PolyMeshModAspectRatioHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModEdgeLength(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def edge_length(self) -> float: ...

    def set_edge_length(self, arg: float, /) -> None: ...

class PolyMeshModEdgeLengthHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModHausdorff(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def tolerance(self) -> float: ...

    def set_tolerance(self, arg: float, /) -> None: ...

class PolyMeshModHausdorffHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModIndependentSets(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

class PolyMeshModIndependentSetsHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModNormalDeviation(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def normal_deviation(self) -> float: ...

    def set_normal_deviation(self, arg: float, /) -> None: ...

class PolyMeshModNormalDeviationHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModNormalFlipping(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def max_normal_deviation(self) -> float: ...

    def set_max_normal_deviation(self, arg: float, /) -> None: ...

class PolyMeshModNormalFlippingHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModProgMeshInfo:
    @property
    def v0(self) -> VertexHandle: ...

    @v0.setter
    def v0(self, arg: VertexHandle, /) -> None: ...

    @property
    def v1(self) -> VertexHandle: ...

    @v1.setter
    def v1(self, arg: VertexHandle, /) -> None: ...

    @property
    def vl(self) -> VertexHandle: ...

    @vl.setter
    def vl(self, arg: VertexHandle, /) -> None: ...

    @property
    def vr(self) -> VertexHandle: ...

    @vr.setter
    def vr(self, arg: VertexHandle, /) -> None: ...

class PolyMeshModProgMesh(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def pmi(self) -> list: ...

    def infolist(self) -> list: ...

    def write(self, arg: str, /) -> bool: ...

class PolyMeshModProgMeshHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModQuadric(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def set_max_err(self, err: float, binary: bool = True) -> None: ...

    def unset_max_err(self) -> None: ...

    def max_err(self) -> float: ...

class PolyMeshModQuadricHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

class PolyMeshModRoundness(PolyMeshModBase):
    def __init__(self, arg: PolyMesh, /) -> None: ...

    def set_min_angle(self, arg0: float, arg1: bool, /) -> None: ...

    def set_min_roundness(self, min_roundness: float, binary: bool = True) -> None: ...

    def unset_min_roundness(self) -> None: ...

    def roundness(self, arg0: "OpenMesh::VectorT<float, 3>", arg1: "OpenMesh::VectorT<float, 3>", arg2: "OpenMesh::VectorT<float, 3>", /) -> float: ...

class PolyMeshModRoundnessHandle:
    def __init__(self) -> None: ...

    def is_valid(self) -> bool: ...

def to_mesh_data(trimesh: TriMesh) -> MeshData:
    """Convert TriMesh to tensor-backed MeshData"""

def from_mesh_data(mesh_data: MeshData) -> TriMesh:
    """Convert MeshData to TriMesh"""

def read_mesh(path: str) -> MeshData:
    """Read a mesh file into MeshData (auto-computes normals if missing)"""
